### ISSUE TITLE
Add "Specification Sub Type" to Offerings Tab

### ISSUE THREAD

**Issue by leothelocust** [sashavmorozov/vlocity-epc-on-steroids#215]
I've figured this out for myself, but I feel like this would be helpful to others and would avoid having to configure this for each environment / worksheet going forward.

Please consider adding "Specification Sub Type" to the `Offerings` tab in the sheet.  I've been able to get it working myself by adding the appropriate field in the DataRaptor as shown below:
![Screen Shot 2022-05-25 at 12 02 43 PM](https://user-images.githubusercontent.com/4381907/170320509-288669f8-22e8-44ac-b88d-6d72b9544f67.png)

And additionally added the column "Specification Sub Type" in the `Offerings` tab in the EPC sheet.
![image](https://user-images.githubusercontent.com/4381907/170320430-47a73c39-d233-4139-aa46-95925cf350fa.png)

In order to get the list to only allow `Simple` and `Bundle` I've just edited the "Data Validation" on the cell to look like the following:
![Screen Shot 2022-05-25 at 12 08 06 PM](https://user-images.githubusercontent.com/4381907/170320964-bce3b1ec-ef50-4ac0-8f42-9a89ac25478c.png)

_P.S. Thanks for all the amazing work on this extraordinary tool!_

**Comment by sashavmorozov** [comment]
This is great, @leothelocust! Will add this to the next version.
Really appreciate the contribution 🙇

**Comment by sashavmorozov** [comment]
fixed and tested in `v1.3`
