### ISSUE TITLE
Installation issue on Spring 22

### ISSUE THREAD

**Issue by MarcoBarna** [sashavmorozov/vlocity-epc-on-steroids#216]
Hi, on the latest Vlocity release (Spring 22) I can't install epc on steroids.

I get the issue that all the apex classes are wrong in their structure
like so (all the apex classes have the issue):

![image](https://user-images.githubusercontent.com/34555572/187204215-f32e1b85-8891-4719-9f11-52acbeec65c2.png)

**Comment by sashavmorozov** [comment]
fixed and tested in `v1.3`
