### ISSUE TITLE
[Deploy] GlobalKey is too long for some dataraptors

### ISSUE THREAD

**Issue by sashavmorozov** [sashavmorozov/vlocity-epc-on-steroids#217]
Hi Sasha, I’m a developer for the Americas Delivery Center on an EPC project with Rashmi Bauskar trying to install EPC On Steroids in a sandbox. I had no problems with it in a CPQ training org, but when trying to migrate with IDX I’m getting the same error on about 28 or so dataraptors.

• DataRaptor/EPC on Steroids_Load Specs Attribute Assignments Definitions -- DataPack &gt;&gt; EPC on Steroids_Load Specs Attribute Assignments Definitions -- Error Message -- Global Key: data value too large: EPC on Steroids_Load Specs Attribute Assignments DefinitionsCustoma0h4J000001APGSQA4Item3 (max length=80)
When I check the GlobalKey field value, it’s always much less than 80 characters. Do you have any experience with this error or have any solutions?

[Slack Message](https://salesforce-internal.slack.com/archives/D04JLFQ3TDJ/p1673490278890439)

**Comment by carlosalonsorodriguez** [comment]
Hi @sashavmorozov 
Same issue here when I tried to install it in a 242 CME Org. 
Can we reduce the name of the DR to have them migrated correctly? Thanks

**Comment by sashavmorozov** [comment]
fixed and tested in `v1.3`
